export const sectionData = [
    {
        id: 1,
        name: 'Basic Tee',
        href: '#',
        imageSrc: '/img/product-1.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '$35',
        color: 'Black',
    },
    {
        id: 2,
        name: 'Basic Tee',
        href: '#',
        imageSrc: '/img/product-2.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '$35',
        color: 'Aspen White',
    },
    {
        id: 3,
        name: 'Basic Tee',
        href: '#',
        imageSrc: '/img/product-4.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '$35',
        color: 'Charcoal',
    },
    {
        id: 4,
        name: 'Artwork Tee',
        href: '#',
        imageSrc: '/img/product-5.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '$35',
        color: 'Iso Dots',
    },
    {
        id: 5,
        name: 'Basic Tee',
        href: '#',
        imageSrc: '/img/product-1.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '$35',
        color: 'Black',
    },
]